### ISSUE TITLE
Version for browser

### ISSUE THREAD

**Issue by mnlipp** [tylingsoft/markdown-it-icons#1]
Is it possible to get a version of the JS that can be loaded in the browser? Some kind of "dist" version as I can get it for [markdown-it](https://github.com/markdown-it/markdown-it/tree/master/dist) itself (and the major plugins).

**Comment by mnlipp** [comment]
I have learned by now that the build command for such a package is `npm run build`. But this produces an error:
```
/home/mnl/tmp/markdown-it-icons/webpack.config.babel.js:1
(function (exports, require, module, __filename, __dirname) { import path from 'path'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
```

**Comment by tylerlong** [comment]
Before building, please update node to latest version.

And I use yarn instead of npm for building.

Prebuilt version is here: https://unpkg.com/markdown-it-icons@0.4.1/dist/

I don't think it will work for browser since it is a node library.

In order to make it work for browser, you need to setup webpack or browerify or parcel in your own project.
